# Generated by Django 4.1.4 on 2022-12-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0002_alter_pacote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacote',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
