# Generated by Django 4.1.4 on 2022-12-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0003_alter_pacote_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionamentoPacote',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('ativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ativos.ativo')),
                ('pacote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ativos.pacote')),
            ],
        ),
    ]
