# Generated by Django 4.1.4 on 2022-12-30 17:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0004_relacionamentopacote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionamentopacote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
