# Generated by Django 4.1.4 on 2022-12-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0005_alter_relacionamentopacote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionamentopacote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
